#!/bin/bash

set -e
set -o nounset

cd "$(dirname "$0")/.."

mkdir -p tmp

cargo build --release
target/release/advent-of-code-2021 all > tmp/rust.out
ruby ruby/all.rb > tmp/ruby.out

set +e
set -x
diff -u all.txt tmp/ruby.out
diff -u all.txt tmp/rust.out
target/release/advent-of-code-2021 timed
